[theme]

# Primary accent for interactive elements
primaryColor = '#25b89a'

# Background color for the main content area
backgroundColor = '#36454F'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3cab73'

# Color used for almost all text
textColor = '#FAF9F6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"